# Generated by Django 3.2.3 on 2021-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/%Y/%m/%d'),
        ),
    ]
