# Generated by Django 3.2.3 on 2021-06-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_contact'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='images.Contact', to='profiles.Person_profile'),
        ),
    ]
