#docker-compose
version: '3'

services:
  web:
    build: .
    command: python /social-docker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/social-docker
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: