# Generated by Django 3.2.3 on 2021-06-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='discription',
            new_name='description',
        ),
    ]
